#!/usr/bin/env python3
"""Generate Slint color roles from the supplied Material Theme export."""
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parent.parent
data = json.loads((ROOT / "assets/theme/material-tonalSpot.json").read_text())
lines = ["// Generated by scripts/generate_theme.py from material-tonalSpot.json.",
         "export global Monet {", "    in-out property <bool> enabled: true;",
         "    in-out property <bool> dark: true;"]
for role, light in data["schemes"]["light"].items():
    name = re.sub(r"([A-Z])", r"-\1", role).lower()
    dark = data["schemes"]["dark"][role]
    lines.append(f"    out property <color> {name}: dark ? {dark} : {light};")
lines.append("}")
(ROOT / "ui/monet.slint").write_text("\n".join(lines) + "\n")
